[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma db push --skip-generate && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
